// https://en.wikipedia.org/wiki/List_of_Eircode_routing_areas_in_Ireland

export const ROUTING_KEYS = [
  { routingKey: "A92", town: "Ardee", county: "Louth" },
  { routingKey: "Y14", town: "Arklow", county: "Wicklow" },
  { routingKey: "A84", town: "Ashbourne", county: "Meath" },
  { routingKey: "H65", town: "Athenry", county: "Galway" },
  { routingKey: "N37", town: "Athlone", county: "Westmeath" },
  { routingKey: "R14", town: "Athy", county: "Kildare" },
  { routingKey: "K32", town: "Balbriggan", county: "Dublin" },
  { routingKey: "F26", town: "Ballina", county: "Mayo" },
  { routingKey: "H53", town: "Ballinasloe", county: "Galway" },
  { routingKey: "P31", town: "Ballincollig", county: "Cork" },
  { routingKey: "F31", town: "Ballinrobe", county: "Mayo" },
  { routingKey: "A75", town: "Ballybay", county: "Monaghan" },
  { routingKey: "A41", town: "Ballyboughal", county: "Dublin" },
  { routingKey: "F35", town: "Ballyhaunis", county: "Mayo" },
  { routingKey: "F56", town: "Ballymote", county: "Sligo" },
  { routingKey: "P72", town: "Bandon", county: "Cork" },
  { routingKey: "P75", town: "Bantry", county: "Cork" },
  { routingKey: "H14", town: "Belturbet", county: "Cavan" },
  { routingKey: "R42", town: "Birr", county: "Offaly" },
  { routingKey: "A94", town: "Blackrock", county: "Dublin" },
  { routingKey: "A94", town: "Booterstown", county: "Dublin" },
  { routingKey: "F52", town: "Boyle", county: "Roscommon" },
  { routingKey: "A98", town: "Bray", county: "Wicklow" },
  { routingKey: "V23", town: "Caherciveen", county: "Kerry" },
  { routingKey: "E21", town: "Cahir", county: "Tipperary" },
  { routingKey: "R93", town: "Carlow", county: "Carlow" },
  { routingKey: "A81", town: "Carrickmacross", county: "Monaghan" },
  { routingKey: "N41", town: "Carrick-on-Shannon", county: "Leitrim" },
  { routingKey: "E32", town: "Carrick-on-Suir", county: "Tipperary" },
  { routingKey: "P43", town: "Carrigaline", county: "Cork" },
  { routingKey: "E25", town: "Cashel", county: "Tipperary" },
  { routingKey: "F23", town: "Castlebar", county: "Mayo" },
  { routingKey: "A75", town: "Castleblaney", county: "Monaghan" },
  { routingKey: "F45", town: "Castlerea", county: "Roscommon" },
  { routingKey: "H12", town: "Cavan", county: "Cavan" },
  { routingKey: "P56", town: "Charleville", county: "Cork" },
  { routingKey: "F12", town: "Claremorris", county: "Mayo" },
  { routingKey: "H71", town: "Clifden", county: "Galway" },
  { routingKey: "P85", town: "Clonakilty", county: "Cork" },
  { routingKey: "H23", town: "Clones", county: "Monaghan" },
  { routingKey: "E91", town: "Clonmel", county: "Tipperary" },
  { routingKey: "P24", town: "Cobh", county: "Cork" },
  { routingKey: "H16", town: "Cootehill", county: "Cavan" },
  {
    routingKey: "T12",
    town: "Cork (centre and southside), Passage West, Cork Airport",
    county: "Cork",
  },
  { routingKey: "T23", town: "Cork (northside), Blarney", county: "Cork" },
  { routingKey: "P14", town: "Crookstown", county: "Cork" },
  { routingKey: "P32", town: "Donoughmore", county: "Cork" },
  { routingKey: "P47", town: "Dunmanway", county: "Cork" },
  { routingKey: "T56", town: "Watergrasshill", county: "Cork" },
  { routingKey: "T34", town: "Whitechurch", county: "Cork" },
  { routingKey: "R56", town: "Curragh Camp", county: "Kildare" },
  { routingKey: "A63", town: "Delgany", county: "Wicklow" },
  { routingKey: "F94", town: "Donegal", county: "Donegal" },
  { routingKey: "A92", town: "Drogheda", county: "Louth" },
  { routingKey: "D01", town: "Dublin 1", county: "Dublin" },
  { routingKey: "D02", town: "Dublin 2", county: "Dublin" },
  { routingKey: "D03", town: "Dublin 3", county: "Dublin" },
  { routingKey: "D04", town: "Dublin 4", county: "Dublin" },
  { routingKey: "D05", town: "Dublin 5", county: "Dublin" },
  { routingKey: "D06", town: "Dublin 6", county: "Dublin" },
  { routingKey: "D6W", town: "Dublin 6W", county: "Dublin" },
  { routingKey: "D07", town: "Dublin 7", county: "Dublin" },
  { routingKey: "D08", town: "Dublin 8", county: "Dublin" },
  { routingKey: "D09", town: "Dublin 9", county: "Dublin" },
  { routingKey: "D10", town: "Dublin 10", county: "Dublin" },
  { routingKey: "D11", town: "Dublin 11", county: "Dublin" },
  { routingKey: "D12", town: "Dublin 12", county: "Dublin" },
  { routingKey: "D13", town: "Dublin 13", county: "Dublin" },
  { routingKey: "D14", town: "Dublin 14", county: "Dublin" },
  { routingKey: "D15", town: "Dublin 15", county: "Dublin" },
  { routingKey: "D16", town: "Dublin 16", county: "Dublin" },
  { routingKey: "D17", town: "Dublin 17", county: "Dublin" },
  { routingKey: "D18", town: "Dublin 18", county: "Dublin" },
  { routingKey: "D20", town: "Dublin 20", county: "Dublin" },
  { routingKey: "D22", town: "Dublin 22", county: "Dublin" },
  { routingKey: "D24", town: "Dublin 24", county: "Dublin" },
  { routingKey: "A86", town: "Dunboyne", county: "Meath" },
  { routingKey: "A91", town: "Dundalk", county: "Louth" },
  { routingKey: "X35", town: "Dungarvan", county: "Waterford" },
  { routingKey: "A85", town: "Dunshaughlin", county: "Meath" },
  { routingKey: "R45", town: "Edenderry", county: "Meath" },
  { routingKey: "A83", town: "Enfield", county: "Meath" },
  { routingKey: "V95", town: "Ennis", county: "Clare" },
  { routingKey: "Y21", town: "Enniscorthy", county: "Wexford" },
  { routingKey: "P61", town: "Fermoy", county: "Cork" },
  { routingKey: "H91", town: "Galway", county: "Galway" },
  { routingKey: "A42", town: "Garristown", county: "Dublin" },
  { routingKey: "A96", town: "Glenageary", county: "Dublin" },
  { routingKey: "Y25", town: "Gorey", county: "Wexford" },
  { routingKey: "A63", town: "Greystones", county: "Wicklow" },
  { routingKey: "A82", town: "Kells", county: "Meath" },
  { routingKey: "A63", town: "Kilcoole", county: "Wicklow" },
  { routingKey: "R51", town: "Kildare", county: "Kildare" },
  { routingKey: "R95", town: "Kilkenny", county: "Kilkenny" },
  { routingKey: "V93", town: "Killarney", county: "Kerry" },
  { routingKey: "X42", town: "Kilmacthomas", county: "Waterford" },
  { routingKey: "V35", town: "Kilmallock", county: "Limerick" },
  { routingKey: "V15", town: "Kilrush", county: "Clare" },
  { routingKey: "A82", town: "Kingscourt", county: "Cavan" },
  { routingKey: "P17", town: "Kinsale", county: "Cork" },
  { routingKey: "A92", town: "Laytown-Bettystown-Mornington", county: "Meath" },
  { routingKey: "F92", town: "Letterkenny", county: "Donegal" },
  { routingKey: "F93", town: "Lifford", county: "Donegal" },
  { routingKey: "V94", town: "Limerick", county: "Limerick" },
  { routingKey: "V31", town: "Listowel", county: "Kerry" },
  { routingKey: "T45", town: "Little Island", county: "Cork" },
  { routingKey: "N39", town: "Longford", county: "Longford" },
  { routingKey: "H62", town: "Loughrea", county: "Galway" },
  { routingKey: "K78", town: "Lucan", county: "Dublin" },
  { routingKey: "K45", town: "Lusk", county: "Dublin" },
  { routingKey: "P12", town: "Macroom", county: "Cork" },
  { routingKey: "K36", town: "Malahide", county: "Dublin" },
  { routingKey: "P51", town: "Mallow", county: "Cork" },
  { routingKey: "W23", town: "Maynooth", county: "Kildare" },
  { routingKey: "P25", town: "Midleton", county: "Cork" },
  { routingKey: "P67", town: "Mitchelstown", county: "Cork" },
  { routingKey: "H18", town: "Monaghan", county: "Monaghan" },
  { routingKey: "W34", town: "Monasterevin", county: "Kildare" },
  { routingKey: "A94", town: "Monkstown", county: "Dublin" },
  { routingKey: "R21", town: "Muine Bheag", county: "Carlow" },
  { routingKey: "N91", town: "Mullingar", county: "Westmeath" },
  { routingKey: "W91", town: "Naas", county: "Kildare" },
  { routingKey: "C15", town: "Navan", county: "Meath" },
  { routingKey: "E45", town: "Nenagh", county: "Tipperary" },
  { routingKey: "Y34", town: "New Ross", county: "Wexford" },
  { routingKey: "W12", town: "Newbridge", county: "Kildare" },
  { routingKey: "A63", town: "Newcastle", county: "Wicklow" },
  { routingKey: "V42", town: "Newcastle West", county: "Limerick" },
  { routingKey: "A63", town: "Newtownmountkennedy", county: "Wicklow" },
  { routingKey: "A45", town: "Oldtown", county: "Dublin" },
  { routingKey: "R32", town: "Portlaoise", county: "Laois" },
  { routingKey: "A67", town: "Rathnew", county: "Wicklow" },
  { routingKey: "A85", town: "Ratoath", county: "Meath" },
  { routingKey: "F42", town: "Roscommon", county: "Roscommon" },
  { routingKey: "E53", town: "Roscrea", county: "Tipperary" },
  { routingKey: "K56", town: "Rush", county: "Dublin" },
  { routingKey: "V14", town: "Shannon", county: "Clare" },
  { routingKey: "K34", town: "Skerries", county: "Dublin" },
  { routingKey: "P81", town: "Skibbereen", county: "Cork" },
  { routingKey: "F91", town: "Sligo", county: "Sligo" },
  { routingKey: "A83", town: "Summerhill", county: "Meath" },
  { routingKey: "K67", town: "Swords and Dublin Airport", county: "Dublin" },
  { routingKey: "E41", town: "Thurles", county: "Tipperary" },
  { routingKey: "E34", town: "Tipperary", county: "Tipperary" },
  { routingKey: "V92", town: "Tralee", county: "Kerry" },
  { routingKey: "H54", town: "Tuam", county: "Galway" },
  { routingKey: "R35", town: "Tullamore", county: "Offaly" },
  { routingKey: "A82", town: "Virginia", county: "Cavan" },
  { routingKey: "X91", town: "Waterford", county: "Waterford" },
  { routingKey: "F28", town: "Westport", county: "Mayo" },
  { routingKey: "Y35", town: "Wexford", county: "Wexford" },
  { routingKey: "A67", town: "Wicklow", county: "Wicklow" },
  { routingKey: "P36", town: "Youghal", county: "Cork" },
];
